#CHÚ Ý!! Bạn chỉ nên sửa những config dưới đây lúc mới cài plugin này
#Vì khi sửa, những item cũ với dữ liệu ngày tháng cũ sẽ trở thành vĩnh viễn!
#=========================

#Kiểm tra tất cả lore hay chỉ kiểm tra dòng cuối
#Nên bật tính năng này nếu bạn xài plugin can thiệp vào lore như soulbound hoặc khảm trang bị
#Nếu tính năng này được bật, dòng static-line sẽ xuất hiện để xác định dòng dữ liệu ngày tháng
check-all-lore: true

#Định dạng ngày tháng, khuyến cáo nên để nguyên
#Tham khảo thêm định dạng ngày tháng tại: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
date-format: dd-MM-yyyy HH:mm

#=========================
locale:
 prefix: '&f&l[&e&lTimedItems&f&l] '
 expired: '&b&lVật phẩm %vp &b&lcủa bạn đã hết hạn sử dụng!'
 static-line: '&a&l[Hàng có thời hạn]'
 unactivated: '&eThời hạn: '
 activated: '&eHết hạn: '
 extend-lock: '&c&l[Không thể gia hạn]'

#Cho phép gia hạn bằng phụ kiện gia hạn?
allow-extender: true
#Cho phép cộng dồn ngày item cùng loại?
allow-extends: true

#=========================
#Thông tin của phụ kiện gia hạn
#Bạn có thể sửa lore hoặc thêm enchant tùy thích, miễn là giữ lại tên item như config dưới đây.
extender:
 name: '&b&lPhụ kiện gia hạn'
 #Khuyến cáo nên để nguyên material
 #Danh sách material: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
 material: WATCH
 lores:
 - '&eGia hạn items có thời hạn,'
 - '&emột phụ kiện gia hạn một ngày.'
 - '&eKéo thả vào item cần gia hạn.' 
 #Số ngày để item trở thành vĩnh viễn, chỉnh thành 99999 nếu muốn bỏ chức năng này.
 days-to-perm: 1000